### PR TITLE
Add --all option to README.md

### PR DESCRIPTION
**Pull request by kevinwaddle**
Also add mention that the bookmarks html will import into Firefox as well.

### CODE REVIEW

**Comment by csu** [comment]
This section of the README should exactly match the output of running `export_saved.py --help`.

**Comment by csu** [comment]
(You can add the Firefox mention to the description in the script, then run it with `--help`, then copy/paste that output into the README, and then those changes should suffice)

**Comment by kevinwaddle** [comment]
Gotcha! Should be corrected now.

**Comment by csu** [comment]
Thanks! Merged

**Pull request merged**
