### PR TITLE
Set default encoding to UTF8

### PR DESCRIPTION
**Pull request by jasonsmedvik**
This helped me with errors I was getting related to utf-8 characters

### CODE REVIEW

**Comment by rachmadaniHaryono** [comment]
hi @jasonsmedvik, i'm not quite sure if it is the fix for every python version. from this SO link it is very discouraged to use it http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

>Also, the use of sys.setdefaultencoding() has always been discouraged, and it has become a no-op in py3k. The encoding of py3k is hard-wired to "utf-8" and changing it raises an error.

also test automation is only on py3 for now. if you want to fix it and add python2.7 test, please check the test code and change it once again.

**Comment by jasonsmedvik** [comment]
hi there, Yes it certainly seems it is strongly discouraged. This is certainly not the correct fix. Is there any easy fix to make this work out-of-the-box with 2.6, 2.7 and 3.x? The only other fix I could get working for 2.7 was to manually modify /usr/lib/python2.x/site.py changing the if 0 to if  1:
```
encoding = "ascii" # Default value set by _PyUnicode_Init()
    if 0:
        # Enable to support locale aware default string encodings.
        import locale
        loc = locale.getdefaultlocale()
        if loc[1]:
            encoding = loc[1]
```

**Comment by rachmadaniHaryono** [comment]
i think that is also discouraged to change the installed python directly. 

you have to know which line causing that error. after that just use catch exception and decode/encode the required variable (most of the time)

or you can just use python3?

**Comment by jasonsmedvik** [comment]
That makes sense.

The line in question (around 194)
```
 # Fix possible buggy utf-8
        title = i.title.encode('utf-8').decode('utf-8')
        logging.debug('title: {}'.format(title)) # << This Line
```

Would try catch work? What would the title become if it is unable to successfully remove all unicode via encode.decode?

Yes it is true: simply using python3 works and is probably the easiest solution.

**Comment by rachmadaniHaryono** [comment]
From the look of it, it is actually python2 code which never work on python2. Python 3 care less about encoding, because it just UTF8. 

>What would the title become if it is unable to successfully remove all unicode via encode.decode?

Depend on second parameter in encode /decode. Example encode (see 'strict', 'ignore') 

https://docs.python.org/3/howto/unicode.html#converting-to-bytes

**Comment by csu** [comment]
For Python 2, we should use UTF-8 everywhere and read/write to the csv as UTF-8. See the `UnicodeReader` and `UnicodeWriter` examples here: https://docs.python.org/2.7/library/csv.html#examples and issue #34. Closing this pull request for now as this is not the change to fix the problem.

**Pull request closed without merging**
