### PR TITLE
Add test

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
- testing using pytest and flake8.
- travis.yml for travis-ci automation test. (not yet tested with travis-ci)
- bookmark folder is [sorted for consistent testing](https://github.com/csu/export-saved-reddit/compare/master...rachmadaniHaryono:add-test?expand=1#diff-89680f92157ef6acd1c0c0995bb03009R52)

### CODE REVIEW

**Comment by csu** [comment]
This is great! Could you resolve the merge conflict in your branch? I can merge it after that.

**Comment by rachmadaniHaryono** [comment]
@csu it is done. the file is renamed for testing so maybe the readme need to be updated later.

**Comment by csu** [comment]
Looks good! Thanks @rachmadaniHaryono! Merging now.

**Comment by csu** [comment]
Connected Travis CI as well: https://travis-ci.org/csu/export-saved-reddit

**Comment by rachmadaniHaryono** [comment]
so i think #22 is solved. you can also add badge from travis-ci.

on travis.yml there is also codecov integration, which you can enabled by uncomment on `after_success` section

**Pull request merged**
